### PR TITLE
tickets/PREOPS-5245: Add support for reading visits from ConsDB

### PR DESCRIPTION
**Pull request by ehneilsen**
This will only work after the merge of a corresponding PR in rubin_scheduler.

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
This also looks fine, rerunning CI at https://github.com/lsst/schedview/actions/runs/10822666752 to check.

**Comment by rhiannonlynne** [comment]
CI still fails after update, but I'm not sure why. test_scheduler is indicating there is not a scheduler_note in the output, which seems unusual.

**Review by rhiannonlynne — CHANGES_REQUESTED** [review]
unit test failure needs attention

**Comment by ehneilsen** [comment]
After rebase onto a main after the merge of PREOPS-4102, CI passes.

**Review by rhiannonlynne — APPROVED** [review]

**Pull request merged**
