### PR TITLE
PREOPS-4935: Improve logging

### PR DESCRIPTION
**Pull request by alserene**
Improve logging within the dashboard’s custom debugging panel and also in stderr.
- Add more logging messages throughout code.
- Send logging information to stderr (as well as dashboard debugging panel) using Python’s inbuilt logger module.
- Prevent debugging messages from spilling outside debugger area.
- Improve formatting of dashboard debugger.

### CODE REVIEW

**Review by ehneilsen — COMMENTED** [review]
Is writing directly to stderr really the best way to handle this? Wouldn't using the python logger configured with an appropriate handler be more flexible if we need to do something else later?

**Comment by alserene** [comment]
> Is writing directly to stderr really the best way to handle this? Wouldn't using the python logger configured with an appropriate handler be more flexible if we need to do something else later?

Sure, I can implement something like this.

**Review by ehneilsen — APPROVED** [review]
Looks good! This is exactly what I had in mind.

**Review by emanehab99 — APPROVED** [review]
Looks good! Thanks Alice

**Pull request merged**
