### PR TITLE
PREOPS-4832 Add a button to reset dashboard to initial load conditions

### PR DESCRIPTION
**Pull request by emanehab99**
Add a button to reload a pickle file to restore original loading condition

### CODE REVIEW

**Comment by emanehab99** [comment]
@ehneilsen I'm not sure what is wrong with the tests. I guess it's something conda related. Can you please check and let me know what's happening?

**Comment by ehneilsen** [comment]
> @ehneilsen I'm not sure what is wrong with the tests. I guess it's something conda related. Can you please check and let me know what's happening?

pytest just released version 8.0.0, which isn't backward compatible.

**Comment by emanehab99** [comment]
@ehneilsen I've made the change to reset the basis function order whenever the file is reloaded. I also copied a change you made to `test-requirements.txt `to use `pytest < 8.0` but it doesn't seem to fix the CI. Anything else I can do?

**Comment by ehneilsen** [comment]
There was also a couple of updates needed to make schedview compatible with the latest version of rubin_scheduler. I merged the PRs to make these fixes onto main this morning, so if you rebase it should fix the issue.

**Pull request merged**
