### PR TITLE
PREOPS-5286: Add Playwright end-to-end tests

### PR DESCRIPTION
**Pull request by alserene**
Created Playwright end-to-end tests for different operational modes. Documentation for installation, execution, and debugging is in playwright_testing.rst.

Tests are disabled by default to minimise workflow runtime and prevent artifact failures due to server load variations. To run tests manually, set ENABLE_PLAYWRIGHT_TESTS=1.

### CODE REVIEW

**Comment by alserene** [comment]
@ehneilsen I'm not too sure how to fix the workflow errors `ModuleNotFoundError: No module named 'playwright'`. Any ideas?

I added
```
- name: Install playwright browsers
        run: |
          pip install playwright
          python -m playwright install --with-deps
```
to `test_and_build.yaml` and I also added playwright to `test-requirements.txt`.
playwright is now showing up in the Conda list, but, still, the error appears.

I'm not super familiar with GitHub workflows so this could be an easy fix.

**Comment by ehneilsen** [comment]
> @ehneilsen There is also this error. I want to check with you if this code correction should be made here since this file was not modified in this PR.
> 
> ```
> schedview/app/scheduler_dashboard/scheduler_dashboard.py:273:12: E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
>     |
> [27](https://github.com/lsst/schedview/actions/runs/9788750126/job/27027344464?pr=95#step:3:29)2 |         # Current fix for _conditions.mjd having different datatypes.
> 273 |         if type(self._conditions._mjd) == np.ndarray:
>     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ E721
> 274 |             self._conditions._mjd = self._conditions._mjd[0]
> ```

Fixing this to use is instead of == would be fine.

**Comment by ehneilsen** [comment]
> @ehneilsen I'm not too sure how to fix the workflow errors `ModuleNotFoundError: No module named 'playwright'`. Any ideas?

It looks like you figured this out? I see that the playwright tests are being run in the github CI, and that they are making it some way into the tests (with several asserts being passed successfully) before failing [here](https://github.com/lsst/schedview/actions/runs/9832030930/job/27140227805?pr=95#step:10:213).

**Review by ehneilsen — APPROVED** [review]
Looks good.

**Pull request merged**
